language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools

    - build-tools-25.0.0
    - android-25

    - extra-android-m2repository

before_script:
  - echo 'Running tests...'

script: ./gradlew test
